### PR TITLE
MCW Microservices architecture June 2019 refresh

### PR DESCRIPTION
**Pull request by rdiazconcha**

### CODE REVIEW

**Comment by waltermyersiii** [comment]
Need to include install of .NET Core 2.2. Also, the updated code Rodrigo provided is here: https://1drv.ms/u/s!AinjixVrYGV1gqRchSKWEOydFWbkqw?e=ErIHxq.

**Comment by waltermyersiii** [comment]
So is the website in the lab supposed to be ASP.NET 4.x or ASP.NET 2.2? Currently it is ASP.NET 4.x which doesn't reflect the direction of the WDS. We need to be more explicit about ASP.NET 2.x in the WDS.

**Comment by rdiazconcha** [comment]
> So is the website in the lab supposed to be ASP.NET 4.x or ASP.NET 2.2? Currently it is ASP.NET 4.x which doesn't reflect the direction of the WDS. We need to be more explicit about ASP.NET 2.x in the WDS.

Yes, the website is based on ASP.NET 4.6, since it's Contoso's current web application.  The only projects based on ASP.NET Core are the Events and Orders microservices.

**Comment by waltermyersiii** [comment]
Please change any references of "in the other hand" to "on the other hand" in the lab.

**Comment by waltermyersiii** [comment]
All looks good!

**Comment by DawnmarieDesJardins** [comment]
@rdiazconcha 
We have lead approval to finalize this update.  Please address and close the current open issues, incorporate lead feedback sent via email, and review for spelling/punctuation/compliance.  When ready for QC/merge, please assign the PR to me.  
Thank you! Dawnmarie

**Pull request merged**
